backend:
  name: github
  repo: mo2iairi/airi-press
  branch: master
  site_url: https://mo2iairi.github.io/airi-press
  base_url: https://mo2iairi.github.io/airi-press
  
media_folder: "public/img/uploads"
public_folder: "/img/uploads"

collections:
  - name: "posts"
    label: "Posts"
    folder: "public/posts"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Layout", name: "layout", widget: "hidden", default: "post"}
      - {label: "ID", name: "id", widget: "string"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime", format: "YYYY-MM-DD", dateFormat: "YYYY-MM-DD", timeFormat: false}
      - {label: "Category", name: "category", widget: "string", default: "General"}
      - {label: "Tags", name: "tags", widget: "list", default: ["blog"]}
      - {label: "Cover Image", name: "imageUrl", widget: "image", required: false}
      - {label: "Description", name: "description", widget: "text", required: false}
      - {label: "Pinned Weight", name: "pinnedWeight", widget: "number", default: 0, value_type: "int"}
      - {label: "Body", name: "body", widget: "markdown"}
